#!/usr/bin/env bash
# Generate readme-preview/ thumbnails from top-level wallpapers and update README.md.
# Requires ImageMagick (magick). Run from repo root.

set -e
cd "$(git rev-parse --show-toplevel)"
PREVIEW_DIR=.github/readme-preview
# 16:9 thumbnails
THUMB_W=320
THUMB_H=180
QUALITY=82

shopt -s nullglob
mkdir -p "$PREVIEW_DIR"

for f in *.jpg *.jpeg *.png; do
  base=${f%.*}
  thumb="$PREVIEW_DIR/${base}.jpg"
  if [ ! -f "$thumb" ] || [ "$f" -nt "$thumb" ]; then
    magick "$f" -auto-orient -resize "${THUMB_W}x${THUMB_H}^" -gravity center -extent "${THUMB_W}x${THUMB_H}" -quality "$QUALITY" "$thumb"
    echo "  $f -> $thumb"
  fi
done

# Build README with preview grid: 3 per row, thumb links to full-res
cat > README.md << 'README_HEAD'
# Wallpapers

Preview thumbnails (click for full resolution). Generated by \`.github/scripts/generate-previews.sh\` or the **Update preview thumbnails** workflow.

README_HEAD

echo '<table align="center"><tr>' >> README.md
i=0
for f in *.jpg *.jpeg *.png; do
  base=${f%.*}
  thumb="$PREVIEW_DIR/${base}.jpg"
  [ -f "$thumb" ] || continue
  [ $i -gt 0 ] && [ $((i % 3)) -eq 0 ] && echo '</tr><tr>' >> README.md
  echo "  <td align=\"center\"><a href=\"$f\"><img src=\"$thumb\" width=\"320\" height=\"180\" style=\"object-fit: cover;\" alt=\"$base\"></a></td>" >> README.md
  i=$((i + 1))
done
echo '</tr></table>' >> README.md

echo "Done. README.md and $PREVIEW_DIR/ updated."
