#!/usr/bin/env bash
# Generate readme-preview/ thumbnails from top-level wallpapers and update README.md.
# Requires ImageMagick (magick). Run from repo root.

set -e
cd "$(git rev-parse --show-toplevel)"
PREVIEW_DIR=readme-preview
MAX_WIDTH=320
QUALITY=82

shopt -s nullglob
mkdir -p "$PREVIEW_DIR"

for f in *.jpg *.jpeg *.png; do
  base=${f%.*}
  thumb="$PREVIEW_DIR/${base}.jpg"
  if [ ! -f "$thumb" ] || [ "$f" -nt "$thumb" ]; then
    magick "$f" -resize "${MAX_WIDTH}x${MAX_WIDTH}>" -quality "$QUALITY" "$thumb"
    echo "  $f -> $thumb"
  fi
done

# Build README with preview grid (thumb links to full-res)
cat > README.md << 'README_HEAD'
# Wallpapers

Preview thumbnails (click for full resolution). Generated by \`scripts/generate-previews.sh\` or the **Update preview thumbnails** workflow.

README_HEAD

echo '<p align="center">' >> README.md
for f in *.jpg *.jpeg *.png; do
  base=${f%.*}
  thumb="$PREVIEW_DIR/${base}.jpg"
  [ -f "$thumb" ] || continue
  echo "  <a href=\"$f\"><img src=\"$thumb\" width=\"160\" alt=\"$base\"></a>" >> README.md
done
echo '</p>' >> README.md

echo "Done. README.md and $PREVIEW_DIR/ updated."
